.PHONY: all
all:
	@echo "[$(notdir $(CURDIR))] MAKEFLAGS=[$(MAKEFLAGS)]"
	@echo "[$(notdir $(CURDIR))] start $$(date +%T)  (will sleep 5s)"
	@echo VAR1 is $(VAR1)
	@echo WINDIR is $(WINDIR)
	@sleep 5
	@echo "[$(notdir $(CURDIR))] end   $$(date +%T)"
